# This is a basic workflow to help you get started with Actions

name: Run tests on custom Docker image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build the docker image
  build-docker-image:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t custom-pytorch ./lab05/.devcontainer
      - name: Run pytest on the docker image
        run: |
          ./lab05/dr.sh pytest